name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        sm-version: [ '1.10', '1.11' ]
        include:
          - sm-version: "1.11" # https://github.com/rumblefrog/setup-sp/issues/5
            compiler-options: "-i=$includePath"

    name: "Build SM ${{ matrix.sm-version }}"
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup SP
        uses: rumblefrog/setup-sp@v1.1.0
        with:
          version: ${{ matrix.sm-version }}

      - name: Run compiler
        run: |
          wget https://github.com/fuckOff1703/levels-ranks-core/raw/1703/addons/sourcemod/scripting/include/lvl_ranks.inc -O $includePath/lvl_ranks.inc
          bash .github/compile.sh ${{ github.workspace }} ${{ matrix.compiler-options }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: levels-ranks-modules-${{ matrix.sm-version }}-${{ env.GITHUB_SHA_SHORT }}
          path: |
            lr_module_*
            LICENSE

  release:
    name: Release
    if: github.ref_type == 'tag'
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Find Assets
        shell: bash
        run: |
          echo "artifact-1_10=$(find * -maxdepth 0 -type d -name "*1.10*")" >> $GITHUB_ENV
          echo "artifact-1_11=$(find * -maxdepth 0 -type d -name "*1.11*")" >> $GITHUB_ENV
          
      - name: Arhive Assets
        run: |
          zip -r ${{ env.artifact-1_10 }}.zip ${{ env.artifact-1_10 }}
          zip -r ${{ env.artifact-1_11 }}.zip ${{ env.artifact-1_11 }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact-1_10 }}.zip
          asset_name: ${{ env.artifact-1_10 }}.zip
          asset_content_type: application/zip

      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact-1_11 }}.zip
          asset_name: ${{ env.artifact-1_11 }}.zip
          asset_content_type: application/zip